-- ============================================================================
-- 30_itops_demo/08_knowledge_base_search.sql
-- Unstructured knowledge for the agent (the RAG leg): runbooks, policies, KB
-- articles, change implementation plans and MSSP / MSP contract excerpts,
-- indexed by a Cortex Search service.
-- Requires 01. Re-runnable.
-- ============================================================================

USE ROLE cortex_role;
USE WAREHOUSE cortex_wh;
USE SCHEMA COWORK.IT_OPS;

CREATE OR REPLACE TABLE KB_DOCUMENTS (
  doc_id VARCHAR, title VARCHAR, doc_type VARCHAR, related_systems VARCHAR, owner_group VARCHAR,
  last_reviewed DATE, body VARCHAR
);

INSERT INTO KB_DOCUMENTS VALUES
('POL-001','IT Service Level Agreement (SLA) Policy','Policy','ManageEngine ServiceDesk Plus','Service Desk','2026-01-15',
'Priorities and targets in ServiceDesk Plus: Urgent (P1) first response 30 minutes, resolution 6 hours. High (P2) first response 1 hour, resolution 24 hours. Medium (P3) first response 4 hours, resolution 72 hours. Low (P4) first response 8 hours, resolution 120 hours. A request is SLA breached when is_overdue is true (resolved after due_by_time, or still open past due_by_time). SLA compliance = 1 - breached resolved requests / resolved requests; target is 90%. MTTR (mean time to resolve) is measured from created_time to resolved_time for Incidents only. P1 incidents require a major incident bridge and an executive notification within 1 hour.'),
('POL-002','Definition: First Contact Resolution (FCR)','Policy','ManageEngine ServiceDesk Plus','Service Desk','2026-02-01',
'First contact resolution means the request was resolved by the first technician/group it was assigned to, with no reassignment and no reopen. In ServiceDesk Plus technicians tick the FCR checkbox (is_fcr) at resolution; reporting additionally requires zero ASSIGN operations in the request history and is_reopened = false. Target FCR is 65% for the Service Desk group. Reassignments usually indicate wrong initial categorisation or missing runbooks.'),
('POL-003','Change Management Policy (including Emergency Changes)','Policy','ManageEngine ServiceDesk Plus','Change Advisory Board','2026-03-10',
'All production changes require an approved RFC in ServiceDesk Plus. Standard changes are pre-approved. Minor and Major changes require CAB approval and a tested back-out plan. Emergency changes may bypass CAB with verbal approval from the IT Director but MUST have a documented and tested back-out plan, must be applied inside a maintenance window when a Tier 1 system is affected, and require a post-implementation review within 5 business days. A change is failed when closure_code is Failed or Rolled Back. Target change failure rate is below 10%. Tier 1 systems: JD Edwards EnterpriseOne (JDE-SQL01/02, JDE-APP01-03, JDE-BATCH01, JDE-WEB01/02), OneStream, Active Directory, Entra Connect, Remote Access VPN.'),
('RB-101','Runbook: JDE-SQL01 SQL Server cumulative update and rollback','Runbook','JD Edwards EnterpriseOne; SQL Server 2022; JDE-SQL01','Business Applications','2025-11-20',
'Pre-checks: confirm full backup and log backup of JDE databases (JDE_PRODUCTION, JDE_PD920), confirm JDE batch queue is drained, place LogicMonitor device group JDE into SDT (scheduled downtime) to suppress alert noise, notify Finance about month-end blackout dates. Apply CU in a maintenance window only. Do not change TempDB file layout in the same change as a CU. Validation: JDE login, run R0911 journal report, check Page Life Expectancy and blocking. Rollback: uninstall CU via Programs and Features, restore TempDB configuration (8 files, 8 GB each), restart SQL Server and JDE services on JDE-APP01..03, then restart Fabric on-prem data gateway FABRIC-GW01 so the nightly PL_JDE_Ingest_Nightly pipeline can reconnect. Known symptom of a bad TempDB change: lock timeouts on F0911 and gateway error SqlFailedToConnect / SQL error 10060.'),
('RB-102','Runbook: Microsoft Fabric CDW nightly load failure','Runbook','Microsoft Fabric; PL_JDE_Ingest_Nightly; FABRIC-GW01; WH_CDW_Gold; Power BI','Cloud Platform','2026-04-02',
'The corporate data warehouse (CDW) loads nightly: PL_JDE_Ingest_Nightly (02:00 UTC, copies JDE tables through the on-premises data gateway FABRIC-GW01 from JDE-SQL01 into LH_Bronze_JDE) -> NB_Silver_Transform_GL -> PL_Silver_To_Gold (loads WH_CDW_Gold) -> Power BI semantic models SM_Finance_GL, SM_AP_AR and SM_Executive_KPI refresh at 04:15-04:30 UTC. If the ingest fails, downstream steps are cancelled but semantic models still refresh on yesterday''s gold data, so Finance reports look stale without erroring. Steps: check gateway status, check JDE-SQL01 availability in LogicMonitor, rerun pipeline manually after source is healthy, then rerun silver/gold and refresh models. Warn users with a banner on Finance - GL Summary. Avoid running full reloads during business hours; they spike F64 capacity and throttle interactive reports.'),
('RB-103','Runbook: LogicMonitor alert triage and noise reduction','Runbook','LogicMonitor','Infrastructure','2026-05-12',
'LogicMonitor is operated by our managed service provider (MSP). Alert severities: 2 Warning, 3 Error, 4 Critical. An alert is considered noise when it clears in under 15 minutes without acknowledgement or fires during SDT. Current noise ratio is well above the 30% target. Actions: tune WinCPU and WinVolumeUsage thresholds, add alert delay of 10 minutes for flapping datapoints, use SDT during approved changes, and make sure every server in the ServiceDesk Plus CMDB is monitored. The MSP only notifies TAC for Critical alerts on Tier 1 devices; trend analysis is not included in the MSP contract.'),
('RB-201','Runbook: Password spray and account compromise response','Runbook','Microsoft Entra ID; Microsoft Sentinel; Defender XDR','Security','2026-02-20',
'Indicators: many failed sign-ins (error 50126) from a small set of IPs across many accounts in a short period, often from Tor exit ranges (for example 185.220.101.0/24). Response: block the IP ranges with a named location, force password reset for any account with a successful sign-in from those IPs, review Conditional Access coverage, and check service accounts which are commonly excluded from MFA. Do not close a password spray incident as benign until all successful sign-ins from the attacker IPs in the following 30 days have been reviewed. Escalate to TAC Security when a service account is involved.'),
('POL-202','Service Account Security Standard','Policy','Microsoft Entra ID; JD Edwards; Fabric','Security','2025-09-30',
'Service accounts (svc_*) must: be excluded from interactive sign-in, use workload identities or certificates instead of passwords where possible, be restricted by Conditional Access to known Azure IP ranges (20.48.200.0/24), hold least-privilege roles only, and never be granted Contributor on production resource groups. Known gap (open risk RSK-17): svc_jde_integration still uses a password, is excluded from Conditional Access and MFA, and has read access to the Fabric CDW gold warehouse for reconciliation jobs. Remediation is tracked in project MFA for Service Accounts.'),
('KB-301','Microsoft Sentinel and MSSP responsibilities','Contract','Microsoft Sentinel; MSSP','Security','2026-01-05',
'The managed security service provider (MSSP) operates Microsoft Sentinel 24x7 with Tier 1 triage. SLAs: High severity incidents acknowledged in 30 minutes, Medium in 4 hours. The MSSP closes incidents with a classification (TruePositive, BenignPositive, FalsePositive, Undetermined). The MSSP does not correlate across Fabric, Power BI or ServiceDesk Plus data and does not perform proactive threat hunting unless requested. TAC Security reviews all High incidents weekly. Cloud (Azure) coverage was added recently and analytics rules for Fabric and Power BI are custom and still being tuned.'),
('KB-302','Power BI export and data exfiltration controls','Policy','Power BI; Microsoft Fabric','Cloud Platform','2026-06-18',
'Exports to CSV/Excel from Finance reports are allowed for named Finance users only. Service principals and service accounts should not export reports. Tenant setting Export to file is enabled for the Finance security group. A Sentinel analytics rule alerts on more than 3 exports in 15 minutes or on exports from IPs outside corporate ranges (203.0.113.0/24). Fabric warehouse queryinsights shows row counts per query; SELECT * against gold facts returning more than 1 million rows outside the ETL service account is suspicious.'),
('KB-401','Windows Server 2012 R2 decommission plan','Plan','Windows Server 2012 R2; JDE-APP02; JDE-APP03; JDE-BATCH01; PRINT01','Infrastructure','2026-05-30',
'Windows Server 2012 R2 reached end of extended support on 2023-10-10. Remaining servers: JDE-APP02, JDE-APP03, JDE-BATCH01 (JD Edwards application and batch tier), PRINT01 and several generic SRV hosts. These hosts do not receive security updates without ESU, and Defender for Endpoint on 2012 R2 has limited EDR capabilities. The JDE hosts were not migrated during the JDE upgrade and Azure move because of a batch-scheduler dependency. Target: migrate to Windows Server 2022 before fiscal year end. Tracked in project Windows 2012 Decommission.'),
('KB-402','Software license reclamation SOP','Procedure','Microsoft 365; ManageEngine ServiceDesk Plus','IT Asset Management','2026-03-01',
'A Microsoft 365 license is reclaimable when the assigned user has no activity for 30 days (Graph getM365AppUserDetail lastActivityDate). Monthly: export inactive users, confirm with managers, downgrade E5 to E3 or remove, and reduce prepaid units at true-up. List prices: Microsoft 365 E5 $57, E3 $36, Copilot $30, Power BI Pro $14 per user per month. SDP software licenses with allocation below 60% should be reviewed before renewal (e.g. AutoCAD LT, Tableau Creator, Zoom Workplace).'),
('POL-501','AI Gateway routing and acceptable use policy','Policy','AI Gateway; Microsoft 365 Copilot','Cloud Platform','2026-06-01',
'All generative AI traffic goes through the TAC AI gateway, which classifies prompt complexity (simple, moderate, complex) and routes to the cheapest adequate model: simple -> gpt-4o-mini or claude-haiku-4-5, moderate -> claude-sonnet-4-5 or gpt-5, complex -> claude-opus-4-1 or gpt-5. Users may override routing (route_reason = user_override) only for complex analytical work. Premium model (claude-opus-4-1) spend on simple prompts is considered waste. Monthly department budgets: Sales & Marketing $250, Finance $250, Operations $200, HR $150, IT $300, Executive $100.'),
('KB-601','CMDB data quality standard','Policy','ManageEngine ServiceDesk Plus CMDB; LogicMonitor','IT Asset Management','2026-04-15',
'A CMDB record is complete when it has owner, support group, environment, site, operating system and (for servers) at least one CI relationship. Target completeness 95%. Records not scanned for 30 days are stale. Every production server in ServiceDesk Plus must exist in LogicMonitor and vice versa; network devices monitored in LogicMonitor must be added to the CMDB.'),
('KB-701','Microsoft Fabric capacity management','Runbook','Microsoft Fabric; F64','Cloud Platform','2026-05-05',
'Production workspaces run on capacity tac-fabric-f64 (64 CUs = 5,529,600 CU-seconds per day). Development runs on tac-fabric-f8-dev (pay-as-you-go, paused off-hours). Keep average daily utilization below 70%; above 100% smoothing leads to interactive throttling for report users. Background jobs (pipelines, notebooks, refreshes) should run between 02:00 and 06:00 UTC. Monitor with the Fabric Capacity Metrics app. Consider reserved capacity for production (about 40% saving).'),
('KB-801','Resourcing and project delivery guidelines','Policy','Smartsheet; ManageEngine ServiceDesk Plus','IT PMO','2026-02-10',
'IT PMO tracks projects in the Smartsheet sheet IT PMO Portfolio. A project is late when completed after its Due Date or still open past its Due Date. Target on-time delivery 75%. Engineers should not carry more than 3 active projects while in an on-call rotation, and ticket worklogs should be recorded in ServiceDesk Plus so capacity can be measured. Some infrastructure engineers do not log tickets, so ticket counts under-represent their workload.');

CREATE OR REPLACE CORTEX SEARCH SERVICE IT_OPS_KNOWLEDGE_SEARCH
  ON body
  ATTRIBUTES doc_type, title, related_systems, owner_group
  WAREHOUSE = cortex_wh
  TARGET_LAG = '1 day'
  COMMENT = 'Runbooks, policies, KB articles and contract excerpts for TAC IT operations and security'
AS
SELECT doc_id, title, doc_type, related_systems, owner_group, last_reviewed::VARCHAR AS last_reviewed, body
FROM KB_DOCUMENTS;

GRANT USAGE ON CORTEX SEARCH SERVICE IT_OPS_KNOWLEDGE_SEARCH TO ROLE PUBLIC;
