-- Flattened Access History Views for Security Monitoring
-- These views flatten the complex ARRAY columns from ACCESS_HISTORY
-- Use these for detailed object-level access tracking

USE ROLE cortex_role;
USE SNOWFLAKE_INTELLIGENCE.TOOLS;

-- =====================================================
-- 1. DIRECT OBJECTS ACCESSED (What was directly queried?)
-- =====================================================
CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.ACCESS_DIRECT_OBJECTS_VW AS
SELECT 
    ah.QUERY_ID,
    ah.QUERY_START_TIME,
    ah.USER_NAME,
    obj.value:objectId::NUMBER AS OBJECT_ID,
    obj.value:objectName::STRING AS OBJECT_NAME,
    obj.value:objectDomain::STRING AS OBJECT_TYPE,
    col.value:columnName::STRING AS COLUMN_NAME
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY ah,
     LATERAL FLATTEN(input => ah.DIRECT_OBJECTS_ACCESSED) obj,
     LATERAL FLATTEN(input => obj.value:columns, OUTER => TRUE) col
WHERE ah.QUERY_START_TIME >= DATEADD(day, -90, CURRENT_TIMESTAMP());

COMMENT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.ACCESS_DIRECT_OBJECTS_VW IS 
'Flattened view showing objects directly accessed in queries. One row per object per query.';

-- =====================================================
-- 2. BASE OBJECTS ACCESSED (What base tables were accessed through views?)
-- =====================================================
CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.ACCESS_BASE_OBJECTS_VW AS
SELECT 
    ah.QUERY_ID,
    ah.QUERY_START_TIME,
    ah.USER_NAME,
    obj.value:objectId::NUMBER AS BASE_OBJECT_ID,
    obj.value:objectName::STRING AS BASE_OBJECT_NAME,
    obj.value:objectDomain::STRING AS BASE_OBJECT_TYPE,
    col.value:columnName::STRING AS COLUMN_NAME
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY ah,
     LATERAL FLATTEN(input => ah.BASE_OBJECTS_ACCESSED) obj,
     LATERAL FLATTEN(input => obj.value:columns, OUTER => TRUE) col
WHERE ah.QUERY_START_TIME >= DATEADD(day, -90, CURRENT_TIMESTAMP());

COMMENT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.ACCESS_BASE_OBJECTS_VW IS 
'Flattened view showing base tables accessed (including through views). One row per base object per query.';

-- =====================================================
-- 3. OBJECTS MODIFIED (What was changed?)
-- =====================================================
CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.ACCESS_OBJECTS_MODIFIED_VW AS
SELECT 
    ah.QUERY_ID,
    ah.QUERY_START_TIME,
    ah.USER_NAME,
    obj.value:objectId::NUMBER AS MODIFIED_OBJECT_ID,
    obj.value:objectName::STRING AS MODIFIED_OBJECT_NAME,
    obj.value:objectDomain::STRING AS MODIFIED_OBJECT_TYPE,
    col.value:columnName::STRING AS MODIFIED_COLUMN_NAME
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY ah,
     LATERAL FLATTEN(input => ah.OBJECTS_MODIFIED) obj,
     LATERAL FLATTEN(input => obj.value:columns, OUTER => TRUE) col
WHERE ah.QUERY_START_TIME >= DATEADD(day, -90, CURRENT_TIMESTAMP());

COMMENT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.ACCESS_OBJECTS_MODIFIED_VW IS 
'Flattened view showing objects modified by queries. One row per modified object per query.';

-- ====================VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_ACTIVITY_VW=================================
-- 4. POLICIES REFERENCED (What security policies were applied?)
-- =====================================================
CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.ACCESS_POLICIES_APPLIED_VW AS
SELECT 
    ah.QUERY_ID,
    ah.QUERY_START_TIME,
    ah.USER_NAME,
    pol.value:policyId::NUMBER AS POLICY_ID,
    pol.value:policyName::STRING AS POLICY_NAME,
    pol.value:policyKind::STRING AS POLICY_KIND,
    pol.value:policyStatus::STRING AS POLICY_STATUS,
    pol.value:refColumnName::STRING AS PROTECTED_COLUMN,
    pol.value:refEntityName::STRING AS PROTECTED_OBJECT
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY ah,
     LATERAL FLATTEN(input => ah.POLICIES_REFERENCED) pol
WHERE ah.QUERY_START_TIME >= DATEADD(day, -90, CURRENT_TIMESTAMP());

COMMENT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.ACCESS_POLICIES_APPLIED_VW IS 
'Flattened view showing security policies applied during query execution. One row per policy per query.';

-- =====================================================
-- 5. SECURITY SUMMARY VIEW - Sensitive Table Access
-- =====================================================
CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.SENSITIVE_TABLE_ACCESS_VW AS
SELECT 
    base.QUERY_START_TIME,
    base.USER_NAME,
    base.BASE_OBJECT_NAME AS TABLE_ACCESSED,
    base.COLUMN_NAME,
    qh.QUERY_TEXT,
    qh.EXECUTION_STATUS,
    qh.ROWS_PRODUCED,
    pol.POLICY_NAME,
    pol.POLICY_KIND
FROM SNOWFLAKE_INTELLIGENCE.TOOLS.ACCESS_BASE_OBJECTS_VW base
LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY qh 
    ON base.QUERY_ID = qh.QUERY_ID
LEFT JOIN SNOWFLAKE_INTELLIGENCE.TOOLS.ACCESS_POLICIES_APPLIED_VW pol
    ON base.QUERY_ID = pol.QUERY_ID 
    AND base.COLUMN_NAME = pol.PROTECTED_COLUMN
WHERE base.BASE_OBJECT_NAME ILIKE ANY ('%CUSTOMER%', '%USER%', '%EMPLOYEE%', '%PAYMENT%', '%SSN%', '%CREDIT_CARD%')
ORDER BY base.QUERY_START_TIME DESC;

COMMENT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.SENSITIVE_TABLE_ACCESS_VW IS 
'Security-focused view showing access to potentially sensitive tables with policy enforcement details.';

-- =====================================================
-- 6. LOGIN ACTIVITY SNAPSHOT (Last 7 days via table function)
-- =====================================================
CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_ACTIVITY_VW AS
SELECT
    EVENT_TYPE,
    USER_NAME,
    CLIENT_IP,
    REPORTED_CLIENT_TYPE,
    REPORTED_CLIENT_VERSION,
    IS_SUCCESS,
    ERROR_CODE,
    ERROR_MESSAGE,
    CONNECTION
FROM TABLE(INFORMATION_SCHEMA.LOGIN_HISTORY(RESULT_LIMIT => 10000));

COMMENT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_ACTIVITY_VW IS
'Latest login activity (last 7 days) using LOGIN_HISTORY table function for real-time data. Use for security monitoring of authentication attempts.';

-- =====================================================
-- 7. SESSION ACTIVITY SNAPSHOT (Last 90 days)
-- =====================================================
CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.SESSION_ACTIVITY_VW AS
SELECT
    SESSION_ID,
    CREATED_ON,
    USER_NAME,
    AUTHENTICATION_METHOD,
    LOGIN_EVENT_ID,
    CLIENT_APPLICATION_VERSION,
    CLIENT_APPLICATION_ID,
    CLIENT_ENVIRONMENT,
    CLIENT_BUILD_ID,
    CLIENT_VERSION,
    CLOSED_REASON
FROM SNOWFLAKE.ACCOUNT_USAGE.SESSIONS
WHERE CREATED_ON >= DATEADD(day, -90, CURRENT_TIMESTAMP());

COMMENT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.SESSION_ACTIVITY_VW IS
'Session metadata including authentication method, client details, and closure reason. Use for tracking user session behavior and client application analysis.';

-- =====================================================
-- 8. STAGE INVENTORY SNAPSHOT
-- =====================================================
CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.STAGE_INVENTORY_VW AS
SELECT
    STAGE_NAME,
    STAGE_SCHEMA,
    STAGE_CATALOG,
    STAGE_URL,
    STAGE_TYPE,
    STAGE_REGION,
    STORAGE_INTEGRATION,
    STAGE_OWNER,
    CREATED,
    LAST_ALTERED,
    DELETED
FROM SNOWFLAKE.ACCOUNT_USAGE.STAGES
WHERE STAGE_NAME IS NOT NULL;

COMMENT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.STAGE_INVENTORY_VW IS
'Inventory of stages with integration details and lifecycle timestamps.';

-- =====================================================
-- 9. AUTOMATIC CLUSTERING ACTIVITY SNAPSHOT (Last 90 days)
-- =====================================================
CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.CLUSTERING_ACTIVITY_VW AS
SELECT
    TABLE_NAME,
    SCHEMA_NAME,
    DATABASE_NAME,
    START_TIME,
    END_TIME,
    CREDITS_USED,
    NUM_BYTES_RECLUSTERED,
    NUM_ROWS_RECLUSTERED
FROM SNOWFLAKE.ACCOUNT_USAGE.AUTOMATIC_CLUSTERING_HISTORY
WHERE START_TIME >= DATEADD(day, -90, CURRENT_TIMESTAMP());

COMMENT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.CLUSTERING_ACTIVITY_VW IS
'Automatic clustering activity with credits, bytes, and rows reclustered.';

-- =====================================================
-- 10. ROLE INVENTORY SNAPSHOT
-- =====================================================
CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.ROLE_INVENTORY_VW AS
SELECT
    NAME,
    COMMENT,
    OWNER,
    ROLE_TYPE,
    ROLE_DATABASE_NAME,
    CREATED_ON,
    DELETED_ON
FROM SNOWFLAKE.ACCOUNT_USAGE.ROLES
WHERE NAME IS NOT NULL;

COMMENT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.ROLE_INVENTORY_VW IS
'Current roles including ownership, database scope, and lifecycle timestamps.';

-- =====================================================
-- 11. TASK ACTIVITY SNAPSHOT (Last 90 days)
-- =====================================================
CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.TASK_ACTIVITY_VW AS
SELECT
    NAME,
    DATABASE_NAME,
    SCHEMA_NAME,
    STATE,
    SCHEDULED_TIME,
    COMPLETED_TIME,
    ERROR_CODE,
    ERROR_MESSAGE
FROM SNOWFLAKE.ACCOUNT_USAGE.TASK_HISTORY
WHERE SCHEDULED_TIME >= DATEADD(day, -90, CURRENT_TIMESTAMP());

COMMENT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.TASK_ACTIVITY_VW IS
'Task runs with schedule, execution status, and error diagnostics.';

-- =====================================================
-- 12. WAREHOUSE METERING SNAPSHOT (Last 30 days)
-- =====================================================
CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.WAREHOUSE_METERING_VW AS
SELECT
    WAREHOUSE_NAME,
    START_TIME,
    END_TIME,
    CREDITS_USED,
    CREDITS_USED_COMPUTE,
    CREDITS_USED_CLOUD_SERVICES
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD(day, -30, CURRENT_TIMESTAMP());

COMMENT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.WAREHOUSE_METERING_VW IS
'Warehouse credit usage with compute vs cloud services breakdown.';

-- =====================================================
-- Example Queries
-- =====================================================

-- Example 1: Who accessed the CUSTOMERS table?
-- SELECT * FROM SNOWFLAKE_INTELLIGENCE.TOOLS.ACCESS_BASE_OBJECTS_VW 
-- WHERE BASE_OBJECT_NAME ILIKE '%CUSTOMERS%' 
-- AND QUERY_START_TIME >= DATEADD(day, -7, CURRENT_TIMESTAMP());

-- Example 2: What masking policies were applied today?
-- SELECT * FROM SNOWFLAKE_INTELLIGENCE.TOOLS.ACCESS_POLICIES_APPLIED_VW 
-- WHERE POLICY_KIND = 'MASKING_POLICY' 
-- AND QUERY_START_TIME >= CURRENT_DATE();

-- Example 3: Show all modifications to production tables
-- SELECT * FROM SNOWFLAKE_INTELLIGENCE.TOOLS.ACCESS_OBJECTS_MODIFIED_VW 
-- WHERE MODIFIED_OBJECT_NAME ILIKE 'PROD%' 
-- AND QUERY_START_TIME >= DATEADD(hour, -24, CURRENT_TIMESTAMP());

-- Example 4: Comprehensive sensitive data access report
-- SELECT * FROM SNOWFLAKE_INTELLIGENCE.TOOLS.SENSITIVE_TABLE_ACCESS_VW 
-- WHERE QUERY_START_TIME >= DATEADD(day, -1, CURRENT_TIMESTAMP())
-- ORDER BY ROWS_ACCESSED DESC;

-- Grant access to these views
-- =====================================================
-- 13. FAILED LOGIN SUMMARY - Aggregated Failed Attempts
-- =====================================================
CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.FAILED_LOGIN_SUMMARY_VW AS
SELECT 
    USER_NAME,
    CLIENT_IP,
    REPORTED_CLIENT_TYPE,
    COUNT(*) AS FAILED_ATTEMPT_COUNT,
    COUNT(DISTINCT ERROR_CODE) AS UNIQUE_ERROR_COUNT,
    LISTAGG(DISTINCT ERROR_CODE, ', ') AS ERROR_CODES,
    LISTAGG(DISTINCT ERROR_MESSAGE, ' | ') AS ERROR_MESSAGES,
    MIN(EVENT_TYPE) AS FIRST_EVENT_TYPE,
    MAX(REPORTED_CLIENT_VERSION) AS LATEST_CLIENT_VERSION
FROM SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_ACTIVITY_VW
WHERE IS_SUCCESS = 'NO'
GROUP BY USER_NAME, CLIENT_IP, REPORTED_CLIENT_TYPE
HAVING COUNT(*) >= 1
ORDER BY FAILED_ATTEMPT_COUNT DESC;

COMMENT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.FAILED_LOGIN_SUMMARY_VW IS
'Aggregated failed login attempts grouped by user, IP, and client type. Use for identifying brute force patterns.';

-- =====================================================
-- 14. SUSPICIOUS LOGIN PATTERNS - Brute Force Detection
-- =====================================================
CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.SUSPICIOUS_LOGIN_PATTERNS_VW AS
SELECT 
    USER_NAME,
    CLIENT_IP,
    REPORTED_CLIENT_TYPE,
    COUNT(*) AS ATTEMPT_COUNT,
    SUM(CASE WHEN IS_SUCCESS = 'NO' THEN 1 ELSE 0 END) AS FAILED_COUNT,
    SUM(CASE WHEN IS_SUCCESS = 'YES' THEN 1 ELSE 0 END) AS SUCCESS_COUNT,
    ROUND(SUM(CASE WHEN IS_SUCCESS = 'NO' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS FAILURE_RATE_PCT,
    COUNT(DISTINCT ERROR_CODE) AS UNIQUE_ERROR_TYPES,
    CASE 
        WHEN SUM(CASE WHEN IS_SUCCESS = 'NO' THEN 1 ELSE 0 END) >= 10 THEN 'HIGH'
        WHEN SUM(CASE WHEN IS_SUCCESS = 'NO' THEN 1 ELSE 0 END) >= 5 THEN 'MEDIUM'
        WHEN SUM(CASE WHEN IS_SUCCESS = 'NO' THEN 1 ELSE 0 END) >= 3 THEN 'LOW'
        ELSE 'NORMAL'
    END AS RISK_LEVEL,
    CASE 
        WHEN SUM(CASE WHEN IS_SUCCESS = 'NO' THEN 1 ELSE 0 END) >= 5 
             AND COUNT(DISTINCT USER_NAME) = 1 THEN 'Possible Brute Force (Single User)'
        WHEN COUNT(DISTINCT USER_NAME) >= 5 
             AND COUNT(DISTINCT CLIENT_IP) = 1 THEN 'Possible Brute Force (Multiple Users, Same IP)'
        WHEN SUM(CASE WHEN IS_SUCCESS = 'NO' THEN 1 ELSE 0 END) >= 3 
             AND COUNT(DISTINCT REPORTED_CLIENT_TYPE) > 1 THEN 'Multiple Client Types (Suspicious)'
        ELSE 'Normal Activity'
    END AS THREAT_INDICATOR,
    LISTAGG(DISTINCT ERROR_MESSAGE, ' | ') AS ERROR_DETAILS
FROM SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_ACTIVITY_VW
GROUP BY USER_NAME, CLIENT_IP, REPORTED_CLIENT_TYPE
HAVING SUM(CASE WHEN IS_SUCCESS = 'NO' THEN 1 ELSE 0 END) >= 2
ORDER BY FAILED_COUNT DESC, RISK_LEVEL DESC;

COMMENT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.SUSPICIOUS_LOGIN_PATTERNS_VW IS
'Security-focused view identifying potential brute force attacks with risk scoring and threat indicators.';

-- =====================================================
-- 15. LOGIN SUCCESS RATE BY USER - Authentication Health
-- =====================================================
CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_SUCCESS_RATE_VW AS
SELECT 
    USER_NAME,
    COUNT(*) AS TOTAL_ATTEMPTS,
    SUM(CASE WHEN IS_SUCCESS = 'YES' THEN 1 ELSE 0 END) AS SUCCESSFUL_LOGINS,
    SUM(CASE WHEN IS_SUCCESS = 'NO' THEN 1 ELSE 0 END) AS FAILED_LOGINS,
    ROUND(SUM(CASE WHEN IS_SUCCESS = 'YES' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS SUCCESS_RATE_PCT,
    COUNT(DISTINCT CLIENT_IP) AS UNIQUE_IP_COUNT,
    COUNT(DISTINCT REPORTED_CLIENT_TYPE) AS UNIQUE_CLIENT_TYPES,
    LISTAGG(DISTINCT REPORTED_CLIENT_TYPE, ', ') AS CLIENT_TYPES_USED,
    CASE 
        WHEN SUM(CASE WHEN IS_SUCCESS = 'NO' THEN 1 ELSE 0 END) >= 5 THEN 'HIGH_FAILURE_RATE'
        WHEN SUM(CASE WHEN IS_SUCCESS = 'NO' THEN 1 ELSE 0 END) >= 2 THEN 'MODERATE_FAILURES'
        WHEN SUM(CASE WHEN IS_SUCCESS = 'YES' THEN 1 ELSE 0 END) = COUNT(*) THEN 'ALL_SUCCESS'
        ELSE 'NORMAL'
    END AS USER_STATUS
FROM SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_ACTIVITY_VW
GROUP BY USER_NAME
ORDER BY FAILED_LOGINS DESC, SUCCESS_RATE_PCT ASC;

COMMENT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_SUCCESS_RATE_VW IS
'User-level authentication success metrics for identifying users with login issues or accounts under attack.';

-- =====================================================
-- 16. IP ADDRESS ANALYSIS - Reputation and Risk
-- =====================================================
CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_IP_ANALYSIS_VW AS
SELECT 
    CLIENT_IP,
    COUNT(*) AS TOTAL_ATTEMPTS,
    COUNT(DISTINCT USER_NAME) AS UNIQUE_USERS,
    SUM(CASE WHEN IS_SUCCESS = 'YES' THEN 1 ELSE 0 END) AS SUCCESSFUL_ATTEMPTS,
    SUM(CASE WHEN IS_SUCCESS = 'NO' THEN 1 ELSE 0 END) AS FAILED_ATTEMPTS,
    ROUND(SUM(CASE WHEN IS_SUCCESS = 'NO' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS FAILURE_RATE_PCT,
    COUNT(DISTINCT REPORTED_CLIENT_TYPE) AS UNIQUE_CLIENT_TYPES,
    LISTAGG(DISTINCT USER_NAME, ', ') AS USERS_ATTEMPTED,
    LISTAGG(DISTINCT REPORTED_CLIENT_TYPE, ', ') AS CLIENT_TYPES,
    CASE 
        WHEN COUNT(DISTINCT USER_NAME) >= 5 THEN 'MULTIPLE_USERS_HIGH_RISK'
        WHEN SUM(CASE WHEN IS_SUCCESS = 'NO' THEN 1 ELSE 0 END) >= 5 THEN 'HIGH_FAILURE_COUNT'
        WHEN COUNT(DISTINCT REPORTED_CLIENT_TYPE) >= 3 THEN 'MULTIPLE_CLIENT_TYPES'
        ELSE 'NORMAL'
    END AS IP_RISK_LEVEL
FROM SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_ACTIVITY_VW
GROUP BY CLIENT_IP
ORDER BY FAILED_ATTEMPTS DESC, UNIQUE_USERS DESC;

COMMENT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_IP_ANALYSIS_VW IS
'IP-based login analysis for identifying suspicious sources and distributed attacks.';

-- =====================================================
-- 17. CLIENT APPLICATION ANALYSIS - Security Compliance
-- =====================================================
CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_CLIENT_ANALYSIS_VW AS
SELECT 
    REPORTED_CLIENT_TYPE,
    REPORTED_CLIENT_VERSION,
    COUNT(*) AS LOGIN_COUNT,
    COUNT(DISTINCT USER_NAME) AS UNIQUE_USERS,
    COUNT(DISTINCT CLIENT_IP) AS UNIQUE_IPS,
    SUM(CASE WHEN IS_SUCCESS = 'YES' THEN 1 ELSE 0 END) AS SUCCESSFUL_LOGINS,
    SUM(CASE WHEN IS_SUCCESS = 'NO' THEN 1 ELSE 0 END) AS FAILED_LOGINS,
    ROUND(SUM(CASE WHEN IS_SUCCESS = 'YES' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS SUCCESS_RATE_PCT,
    LISTAGG(DISTINCT USER_NAME, ', ') WITHIN GROUP (ORDER BY USER_NAME) AS USERS,
    CASE 
        WHEN REPORTED_CLIENT_TYPE = 'SNOWSQL_CLI' AND REPORTED_CLIENT_VERSION < '1.3.0' THEN 'OUTDATED_VERSION'
        WHEN REPORTED_CLIENT_TYPE ILIKE '%UNKNOWN%' THEN 'UNKNOWN_CLIENT'
        WHEN REPORTED_CLIENT_TYPE ILIKE '%CUSTOM%' THEN 'CUSTOM_CLIENT'
        ELSE 'STANDARD_CLIENT'
    END AS CLIENT_STATUS
FROM SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_ACTIVITY_VW
GROUP BY REPORTED_CLIENT_TYPE, REPORTED_CLIENT_VERSION
ORDER BY LOGIN_COUNT DESC;

COMMENT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_CLIENT_ANALYSIS_VW IS
'Client application and version analysis for authentication security compliance.';

-- =====================================================
-- 18. LOGIN SECURITY DASHBOARD - Executive Summary
-- =====================================================
CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_SECURITY_DASHBOARD_VW AS
SELECT 
    'TOTAL_ATTEMPTS' AS METRIC,
    COUNT(*)::STRING AS VALUE,
    'Total login attempts in last 7 days' AS DESCRIPTION
FROM SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_ACTIVITY_VW
UNION ALL
SELECT 
    'SUCCESSFUL_LOGINS',
    SUM(CASE WHEN IS_SUCCESS = 'YES' THEN 1 ELSE 0 END)::STRING,
    'Successful authentications'
FROM SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_ACTIVITY_VW
UNION ALL
SELECT 
    'FAILED_LOGINS',
    SUM(CASE WHEN IS_SUCCESS = 'NO' THEN 1 ELSE 0 END)::STRING,
    'Failed authentication attempts'
FROM SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_ACTIVITY_VW
UNION ALL
SELECT 
    'SUCCESS_RATE_PCT',
    ROUND(SUM(CASE WHEN IS_SUCCESS = 'YES' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2)::STRING,
    'Overall authentication success rate'
FROM SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_ACTIVITY_VW
UNION ALL
SELECT 
    'UNIQUE_USERS',
    COUNT(DISTINCT USER_NAME)::STRING,
    'Distinct users with login attempts'
FROM SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_ACTIVITY_VW
UNION ALL
SELECT 
    'UNIQUE_IPS',
    COUNT(DISTINCT CLIENT_IP)::STRING,
    'Distinct IP addresses'
FROM SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_ACTIVITY_VW
UNION ALL
SELECT 
    'HIGH_RISK_IPS',
    COUNT(DISTINCT CLIENT_IP)::STRING,
    'IPs with 5+ failed attempts'
FROM SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_ACTIVITY_VW
WHERE IS_SUCCESS = 'NO'
GROUP BY CLIENT_IP
HAVING COUNT(*) >= 5
UNION ALL
SELECT 
    'USERS_WITH_FAILURES',
    COUNT(DISTINCT USER_NAME)::STRING,
    'Users with at least one failed login'
FROM SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_ACTIVITY_VW
WHERE IS_SUCCESS = 'NO'
UNION ALL
SELECT 
    'CLIENT_TYPES',
    COUNT(DISTINCT REPORTED_CLIENT_TYPE)::STRING,
    'Distinct client application types'
FROM SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_ACTIVITY_VW
ORDER BY METRIC;

COMMENT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_SECURITY_DASHBOARD_VW IS
'Comprehensive security metrics dashboard for real-time login activity monitoring.';

-- =====================================================
-- Grant Access to All Views
-- =====================================================
GRANT SELECT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.ACCESS_DIRECT_OBJECTS_VW TO ROLE PUBLIC;
GRANT SELECT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.ACCESS_BASE_OBJECTS_VW TO ROLE PUBLIC;
GRANT SELECT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.ACCESS_OBJECTS_MODIFIED_VW TO ROLE PUBLIC;
GRANT SELECT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.ACCESS_POLICIES_APPLIED_VW TO ROLE PUBLIC;
GRANT SELECT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.SENSITIVE_TABLE_ACCESS_VW TO ROLE PUBLIC;
GRANT SELECT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_ACTIVITY_VW TO ROLE PUBLIC;
GRANT SELECT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.SESSION_ACTIVITY_VW TO ROLE PUBLIC;
GRANT SELECT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.STAGE_INVENTORY_VW TO ROLE PUBLIC;
GRANT SELECT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.CLUSTERING_ACTIVITY_VW TO ROLE PUBLIC;
GRANT SELECT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.ROLE_INVENTORY_VW TO ROLE PUBLIC;
GRANT SELECT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.TASK_ACTIVITY_VW TO ROLE PUBLIC;
GRANT SELECT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.WAREHOUSE_METERING_VW TO ROLE PUBLIC;
GRANT SELECT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.FAILED_LOGIN_SUMMARY_VW TO ROLE PUBLIC;
GRANT SELECT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.SUSPICIOUS_LOGIN_PATTERNS_VW TO ROLE PUBLIC;
GRANT SELECT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_SUCCESS_RATE_VW TO ROLE PUBLIC;
GRANT SELECT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_IP_ANALYSIS_VW TO ROLE PUBLIC;
GRANT SELECT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_CLIENT_ANALYSIS_VW TO ROLE PUBLIC;
GRANT SELECT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.LOGIN_SECURITY_DASHBOARD_VW TO ROLE PUBLIC;

