-- Flattened CloudTrail Logs View (Generic JSON Flattening)
-- This view converts all VARIANT (JSON) columns in ARCHETYPE.SECURITY_DL.CLOUDTRAIL_LOGS
-- into key/path/value rows for easy searching without knowing the JSON schema up front.

USE ROLE cortex_role;
USE SNOWFLAKE_INTELLIGENCE.TOOLS;

-- One row per original CloudTrail row per JSON leaf/node (recursive flatten).
-- Tip: filter to leaf scalars with: WHERE is_leaf
CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.CLOUDTRAIL_LOGS_FLATTENED_VW AS
WITH base AS (
    SELECT
        METADATA,
        TIME,
        CLOUD,
        API,
        DST_ENDPOINT,
        ACTOR,
        HTTP_REQUEST,
        SRC_ENDPOINT,
        IP_ADDRESS,
        SESSION,
        POLICY,
        CLASS_NAME,
        CLASS_UID,
        CATEGORY_UID,
        SEVERITY_ID,
        SEVERITY,
        "USER",
        ACTIVITY_NAME,
        ACTIVITY_ID,
        TYPE_NAME,
        STATUS,
        IS_MFA,
        ACCOUNTID,
        REGION
    FROM ARCHETYPE.SECURITY_DL.CLOUDTRAIL_LOGS
)
SELECT
    b.TIME,
    b.IP_ADDRESS,
    b.CLASS_NAME,
    b.CLASS_UID,
    b.CATEGORY_UID,
    b.SEVERITY_ID,
    b.SEVERITY,
    b.ACTIVITY_NAME,
    b.ACTIVITY_ID,
    b.TYPE_NAME,
    b.STATUS,
    b.IS_MFA,
    b.ACCOUNTID,
    b.REGION,
    'METADATA' AS VARIANT_COL,
    f.PATH::STRING AS JSON_PATH,
    f.KEY::STRING AS JSON_KEY,
    f.INDEX::NUMBER AS ARRAY_INDEX,
    f.SEQ::NUMBER AS SEQ,
    f.THIS AS JSON_CONTAINER,
    f.VALUE AS JSON_VALUE,
    TYPEOF(f.VALUE) AS JSON_VALUE_TYPE,
    (TYPEOF(f.VALUE) NOT IN ('OBJECT', 'ARRAY')) AS IS_LEAF
FROM base b,
     LATERAL FLATTEN(INPUT => b.METADATA, RECURSIVE => TRUE) f

UNION ALL
SELECT
    b.TIME,
    b.IP_ADDRESS,
    b.CLASS_NAME,
    b.CLASS_UID,
    b.CATEGORY_UID,
    b.SEVERITY_ID,
    b.SEVERITY,
    b.ACTIVITY_NAME,
    b.ACTIVITY_ID,
    b.TYPE_NAME,
    b.STATUS,
    b.IS_MFA,
    b.ACCOUNTID,
    b.REGION,
    'CLOUD' AS VARIANT_COL,
    f.PATH::STRING AS JSON_PATH,
    f.KEY::STRING AS JSON_KEY,
    f.INDEX::NUMBER AS ARRAY_INDEX,
    f.SEQ::NUMBER AS SEQ,
    f.THIS AS JSON_CONTAINER,
    f.VALUE AS JSON_VALUE,
    TYPEOF(f.VALUE) AS JSON_VALUE_TYPE,
    (TYPEOF(f.VALUE) NOT IN ('OBJECT', 'ARRAY')) AS IS_LEAF
FROM base b,
     LATERAL FLATTEN(INPUT => b.CLOUD, RECURSIVE => TRUE) f

UNION ALL
SELECT
    b.TIME,
    b.IP_ADDRESS,
    b.CLASS_NAME,
    b.CLASS_UID,
    b.CATEGORY_UID,
    b.SEVERITY_ID,
    b.SEVERITY,
    b.ACTIVITY_NAME,
    b.ACTIVITY_ID,
    b.TYPE_NAME,
    b.STATUS,
    b.IS_MFA,
    b.ACCOUNTID,
    b.REGION,
    'API' AS VARIANT_COL,
    f.PATH::STRING AS JSON_PATH,
    f.KEY::STRING AS JSON_KEY,
    f.INDEX::NUMBER AS ARRAY_INDEX,
    f.SEQ::NUMBER AS SEQ,
    f.THIS AS JSON_CONTAINER,
    f.VALUE AS JSON_VALUE,
    TYPEOF(f.VALUE) AS JSON_VALUE_TYPE,
    (TYPEOF(f.VALUE) NOT IN ('OBJECT', 'ARRAY')) AS IS_LEAF
FROM base b,
     LATERAL FLATTEN(INPUT => b.API, RECURSIVE => TRUE) f

UNION ALL
SELECT
    b.TIME,
    b.IP_ADDRESS,
    b.CLASS_NAME,
    b.CLASS_UID,
    b.CATEGORY_UID,
    b.SEVERITY_ID,
    b.SEVERITY,
    b.ACTIVITY_NAME,
    b.ACTIVITY_ID,
    b.TYPE_NAME,
    b.STATUS,
    b.IS_MFA,
    b.ACCOUNTID,
    b.REGION,
    'DST_ENDPOINT' AS VARIANT_COL,
    f.PATH::STRING AS JSON_PATH,
    f.KEY::STRING AS JSON_KEY,
    f.INDEX::NUMBER AS ARRAY_INDEX,
    f.SEQ::NUMBER AS SEQ,
    f.THIS AS JSON_CONTAINER,
    f.VALUE AS JSON_VALUE,
    TYPEOF(f.VALUE) AS JSON_VALUE_TYPE,
    (TYPEOF(f.VALUE) NOT IN ('OBJECT', 'ARRAY')) AS IS_LEAF
FROM base b,
     LATERAL FLATTEN(INPUT => b.DST_ENDPOINT, RECURSIVE => TRUE) f

UNION ALL
SELECT
    b.TIME,
    b.IP_ADDRESS,
    b.CLASS_NAME,
    b.CLASS_UID,
    b.CATEGORY_UID,
    b.SEVERITY_ID,
    b.SEVERITY,
    b.ACTIVITY_NAME,
    b.ACTIVITY_ID,
    b.TYPE_NAME,
    b.STATUS,
    b.IS_MFA,
    b.ACCOUNTID,
    b.REGION,
    'ACTOR' AS VARIANT_COL,
    f.PATH::STRING AS JSON_PATH,
    f.KEY::STRING AS JSON_KEY,
    f.INDEX::NUMBER AS ARRAY_INDEX,
    f.SEQ::NUMBER AS SEQ,
    f.THIS AS JSON_CONTAINER,
    f.VALUE AS JSON_VALUE,
    TYPEOF(f.VALUE) AS JSON_VALUE_TYPE,
    (TYPEOF(f.VALUE) NOT IN ('OBJECT', 'ARRAY')) AS IS_LEAF
FROM base b,
     LATERAL FLATTEN(INPUT => b.ACTOR, RECURSIVE => TRUE) f

UNION ALL
SELECT
    b.TIME,
    b.IP_ADDRESS,
    b.CLASS_NAME,
    b.CLASS_UID,
    b.CATEGORY_UID,
    b.SEVERITY_ID,
    b.SEVERITY,
    b.ACTIVITY_NAME,
    b.ACTIVITY_ID,
    b.TYPE_NAME,
    b.STATUS,
    b.IS_MFA,
    b.ACCOUNTID,
    b.REGION,
    'HTTP_REQUEST' AS VARIANT_COL,
    f.PATH::STRING AS JSON_PATH,
    f.KEY::STRING AS JSON_KEY,
    f.INDEX::NUMBER AS ARRAY_INDEX,
    f.SEQ::NUMBER AS SEQ,
    f.THIS AS JSON_CONTAINER,
    f.VALUE AS JSON_VALUE,
    TYPEOF(f.VALUE) AS JSON_VALUE_TYPE,
    (TYPEOF(f.VALUE) NOT IN ('OBJECT', 'ARRAY')) AS IS_LEAF
FROM base b,
     LATERAL FLATTEN(INPUT => b.HTTP_REQUEST, RECURSIVE => TRUE) f

UNION ALL
SELECT
    b.TIME,
    b.IP_ADDRESS,
    b.CLASS_NAME,
    b.CLASS_UID,
    b.CATEGORY_UID,
    b.SEVERITY_ID,
    b.SEVERITY,
    b.ACTIVITY_NAME,
    b.ACTIVITY_ID,
    b.TYPE_NAME,
    b.STATUS,
    b.IS_MFA,
    b.ACCOUNTID,
    b.REGION,
    'SRC_ENDPOINT' AS VARIANT_COL,
    f.PATH::STRING AS JSON_PATH,
    f.KEY::STRING AS JSON_KEY,
    f.INDEX::NUMBER AS ARRAY_INDEX,
    f.SEQ::NUMBER AS SEQ,
    f.THIS AS JSON_CONTAINER,
    f.VALUE AS JSON_VALUE,
    TYPEOF(f.VALUE) AS JSON_VALUE_TYPE,
    (TYPEOF(f.VALUE) NOT IN ('OBJECT', 'ARRAY')) AS IS_LEAF
FROM base b,
     LATERAL FLATTEN(INPUT => b.SRC_ENDPOINT, RECURSIVE => TRUE) f

UNION ALL
SELECT
    b.TIME,
    b.IP_ADDRESS,
    b.CLASS_NAME,
    b.CLASS_UID,
    b.CATEGORY_UID,
    b.SEVERITY_ID,
    b.SEVERITY,
    b.ACTIVITY_NAME,
    b.ACTIVITY_ID,
    b.TYPE_NAME,
    b.STATUS,
    b.IS_MFA,
    b.ACCOUNTID,
    b.REGION,
    'SESSION' AS VARIANT_COL,
    f.PATH::STRING AS JSON_PATH,
    f.KEY::STRING AS JSON_KEY,
    f.INDEX::NUMBER AS ARRAY_INDEX,
    f.SEQ::NUMBER AS SEQ,
    f.THIS AS JSON_CONTAINER,
    f.VALUE AS JSON_VALUE,
    TYPEOF(f.VALUE) AS JSON_VALUE_TYPE,
    (TYPEOF(f.VALUE) NOT IN ('OBJECT', 'ARRAY')) AS IS_LEAF
FROM base b,
     LATERAL FLATTEN(INPUT => b.SESSION, RECURSIVE => TRUE) f

UNION ALL
SELECT
    b.TIME,
    b.IP_ADDRESS,
    b.CLASS_NAME,
    b.CLASS_UID,
    b.CATEGORY_UID,
    b.SEVERITY_ID,
    b.SEVERITY,
    b.ACTIVITY_NAME,
    b.ACTIVITY_ID,
    b.TYPE_NAME,
    b.STATUS,
    b.IS_MFA,
    b.ACCOUNTID,
    b.REGION,
    'POLICY' AS VARIANT_COL,
    f.PATH::STRING AS JSON_PATH,
    f.KEY::STRING AS JSON_KEY,
    f.INDEX::NUMBER AS ARRAY_INDEX,
    f.SEQ::NUMBER AS SEQ,
    f.THIS AS JSON_CONTAINER,
    f.VALUE AS JSON_VALUE,
    TYPEOF(f.VALUE) AS JSON_VALUE_TYPE,
    (TYPEOF(f.VALUE) NOT IN ('OBJECT', 'ARRAY')) AS IS_LEAF
FROM base b,
     LATERAL FLATTEN(INPUT => b.POLICY, RECURSIVE => TRUE) f

UNION ALL
SELECT
    b.TIME,
    b.IP_ADDRESS,
    b.CLASS_NAME,
    b.CLASS_UID,
    b.CATEGORY_UID,
    b.SEVERITY_ID,
    b.SEVERITY,
    b.ACTIVITY_NAME,
    b.ACTIVITY_ID,
    b.TYPE_NAME,
    b.STATUS,
    b.IS_MFA,
    b.ACCOUNTID,
    b.REGION,
    'USER' AS VARIANT_COL,
    f.PATH::STRING AS JSON_PATH,
    f.KEY::STRING AS JSON_KEY,
    f.INDEX::NUMBER AS ARRAY_INDEX,
    f.SEQ::NUMBER AS SEQ,
    f.THIS AS JSON_CONTAINER,
    f.VALUE AS JSON_VALUE,
    TYPEOF(f.VALUE) AS JSON_VALUE_TYPE,
    (TYPEOF(f.VALUE) NOT IN ('OBJECT', 'ARRAY')) AS IS_LEAF
FROM base b,
     LATERAL FLATTEN(INPUT => b."USER", RECURSIVE => TRUE) f
;

COMMENT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.CLOUDTRAIL_LOGS_FLATTENED_VW IS
'Generic recursive flatten of ARCHETYPE.SECURITY_DL.CLOUDTRAIL_LOGS VARIANT columns. One row per event per JSON node/leaf with VARIANT_COL + JSON_PATH + JSON_KEY + JSON_VALUE.';

GRANT SELECT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.CLOUDTRAIL_LOGS_FLATTENED_VW TO ROLE PUBLIC;


