-- accept terms
CALL SYSTEM$ACCEPT_LEGAL_TERMS('DATA_EXCHANGE_LISTING', 'GZSTZ67BY9OQ4');
-- create a database that includes Cortex search
CREATE OR REPLACE DATABASE IDENTIFIER('"SNOWFLAKE_DOCUMENTATION"') 
    FROM LISTING IDENTIFIER('"GZSTZ67BY9OQ4"');
-- grant usage to the public so all can use Snowflake documentation
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE_DOCUMENTATION  
    TO ROLE PUBLIC;