-- ============================================================================
-- FLATTENED CLOUDFLARE LOGS (JSON) - Helper View for Snowflake Intelligence
-- ============================================================================
-- Snowflake Intelligence / Semantic Views can't "understand" arbitrary JSON.
-- This view flattens the Cloudflare RAW_EVENT JSON text into path/key/value rows.

USE ROLE cortex_role;
USE SNOWFLAKE_INTELLIGENCE.TOOLS;

CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.CLOUDFLARE_LOGS_FLATTENED_VW AS
WITH base AS (
  SELECT
    EVENT_TIME,
    CLIENT_IP,
    CLIENT_REQUEST_HOST,
    CLIENT_REQUEST_METHOD,
    CLIENT_REQUEST_URI,
    EDGE_RESPONSE_STATUS,
    EDGE_RESPONSE_BYTES,
    CLIENT_COUNTRY,
    CLIENT_ASN,
    EDGE_COLO_CODE,
    RAY_ID,
    SECURITY_ACTION,
    WAF_FLAGS,
    TRY_PARSE_JSON(RAW_EVENT) AS RAW_EVENT_JSON
  FROM SNOWFLAKE_INTELLIGENCE.TOOLS.CLOUDFLARE_LOGS_SOURCE
)
SELECT
  b.EVENT_TIME,
  b.CLIENT_IP,
  b.CLIENT_REQUEST_HOST,
  b.CLIENT_REQUEST_METHOD,
  b.CLIENT_REQUEST_URI,
  b.EDGE_RESPONSE_STATUS,
  b.EDGE_RESPONSE_BYTES,
  b.CLIENT_COUNTRY,
  b.CLIENT_ASN,
  b.EDGE_COLO_CODE,
  b.RAY_ID,
  b.SECURITY_ACTION,
  b.WAF_FLAGS,
  'RAW_EVENT' AS VARIANT_SOURCE,
  f.PATH::STRING AS PATH,
  f.KEY::STRING AS KEY,
  f.INDEX::NUMBER AS ARRAY_INDEX,
  f.SEQ::NUMBER AS SEQ,
  f.VALUE AS VALUE,
  TYPEOF(f.VALUE) AS VALUE_TYPE,
  (TYPEOF(f.VALUE) NOT IN ('OBJECT', 'ARRAY')) AS IS_LEAF
FROM base b,
     LATERAL FLATTEN(INPUT => b.RAW_EVENT_JSON, RECURSIVE => TRUE) f
WHERE b.RAW_EVENT_JSON IS NOT NULL
;

COMMENT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.CLOUDFLARE_LOGS_FLATTENED_VW IS
'Recursive flatten of CLOUDFLARE_LOGS_SOURCE.RAW_EVENT JSON text into path/key/value rows for Snowflake Intelligence.';

GRANT SELECT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.CLOUDFLARE_LOGS_FLATTENED_VW TO ROLE PUBLIC;


