-- ============================================================================
-- FLATTENED NPM SUPPLY CHAIN EVENTS (JSON) - Helper View for Snowflake Intelligence
-- ============================================================================
-- Reference: https://www.ox.security/blog/npm-packages-compromised/
-- Snowflake Intelligence / semantic views can't reliably reason over arbitrary JSON.
-- This view flattens RAW_EVENT_JSON into path/key/value rows.

USE ROLE cortex_role;
USE SNOWFLAKE_INTELLIGENCE.TOOLS;

CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.NPM_PACKAGE_EVENTS_FLATTENED_VW AS
WITH base AS (
  SELECT
    EVENT_TIME,
    ENVIRONMENT,
    HOSTNAME,
    REPOSITORY,
    PIPELINE_ID,
    ACTOR,
    EVENT_TYPE,
    PACKAGE_NAME,
    PACKAGE_VERSION,
    PACKAGE_SCOPE,
    REGISTRY,
    INSTALL_COMMAND,
    SCRIPT_NAME,
    SCRIPT_COMMAND,
    NETWORK_DEST_HOST,
    NETWORK_DEST_PORT,
    INDICATOR_TYPE,
    INDICATOR_SEVERITY,
    CWE_ID,
    CWE_NAME,
    STATUS,
    TRY_PARSE_JSON(RAW_EVENT_JSON) AS RAW_JSON
  FROM SNOWFLAKE_INTELLIGENCE.TOOLS.NPM_PACKAGE_EVENTS_SOURCE
)
SELECT
  b.EVENT_TIME,
  b.ENVIRONMENT,
  b.HOSTNAME,
  b.REPOSITORY,
  b.PIPELINE_ID,
  b.ACTOR,
  b.EVENT_TYPE,
  b.PACKAGE_NAME,
  b.PACKAGE_VERSION,
  b.PACKAGE_SCOPE,
  b.REGISTRY,
  b.INSTALL_COMMAND,
  b.SCRIPT_NAME,
  b.SCRIPT_COMMAND,
  b.NETWORK_DEST_HOST,
  b.NETWORK_DEST_PORT,
  b.INDICATOR_TYPE,
  b.INDICATOR_SEVERITY,
  b.CWE_ID,
  b.CWE_NAME,
  b.STATUS,
  'RAW_EVENT_JSON' AS VARIANT_SOURCE,
  f.PATH::STRING AS PATH,
  f.KEY::STRING AS KEY,
  f.INDEX::NUMBER AS ARRAY_INDEX,
  f.SEQ::NUMBER AS SEQ,
  f.VALUE AS VALUE,
  TYPEOF(f.VALUE) AS VALUE_TYPE,
  (TYPEOF(f.VALUE) NOT IN ('OBJECT','ARRAY')) AS IS_LEAF,
  IFF(TYPEOF(f.VALUE) NOT IN ('OBJECT','ARRAY'), TO_VARCHAR(f.VALUE), NULL) AS LEAF_VALUE
FROM base b,
     LATERAL FLATTEN(INPUT => b.RAW_JSON, RECURSIVE => TRUE) f
WHERE b.RAW_JSON IS NOT NULL
;

COMMENT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.NPM_PACKAGE_EVENTS_FLATTENED_VW IS
'Recursive flatten of npm supply-chain RAW_EVENT_JSON into path/key/value rows for Snowflake Intelligence.';

GRANT SELECT ON VIEW SNOWFLAKE_INTELLIGENCE.TOOLS.NPM_PACKAGE_EVENTS_FLATTENED_VW TO ROLE PUBLIC;


