-- This script checks what columns are actually available in your Snowflake Account Usage tables
-- Run this to see exactly what you can use in your semantic view

USE ROLE ACCOUNTADMIN;
USE SCHEMA SNOWFLAKE.ACCOUNT_USAGE;

-- Check MASKING_POLICIES columns
SELECT 'MASKING_POLICIES' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM SNOWFLAKE.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ACCOUNT_USAGE'
  AND TABLE_NAME = 'MASKING_POLICIES'
ORDER BY ORDINAL_POSITION;

-- Check ROW_ACCESS_POLICIES columns
SELECT 'ROW_ACCESS_POLICIES' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM SNOWFLAKE.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ACCOUNT_USAGE'
  AND TABLE_NAME = 'ROW_ACCESS_POLICIES'
ORDER BY ORDINAL_POSITION;

-- Check PASSWORD_POLICIES columns
SELECT 'PASSWORD_POLICIES' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM SNOWFLAKE.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ACCOUNT_USAGE'
  AND TABLE_NAME = 'PASSWORD_POLICIES'
ORDER BY ORDINAL_POSITION;

-- Check SESSION_POLICIES columns
SELECT 'SESSION_POLICIES' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM SNOWFLAKE.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ACCOUNT_USAGE'
  AND TABLE_NAME = 'SESSION_POLICIES'
ORDER BY ORDINAL_POSITION;

-- Check FUNCTIONS columns
SELECT 'FUNCTIONS' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM SNOWFLAKE.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ACCOUNT_USAGE'
  AND TABLE_NAME = 'FUNCTIONS'
ORDER BY ORDINAL_POSITION;

-- Check USERS columns
SELECT 'USERS' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM SNOWFLAKE.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ACCOUNT_USAGE'
  AND TABLE_NAME = 'USERS'
ORDER BY ORDINAL_POSITION;

-- Check EXTERNAL_ACCESS_HISTORY columns (if it exists)
SELECT 'EXTERNAL_ACCESS_HISTORY' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM SNOWFLAKE.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ACCOUNT_USAGE'
  AND TABLE_NAME = 'EXTERNAL_ACCESS_HISTORY'
ORDER BY ORDINAL_POSITION;

-- Check MATERIALIZED_VIEW_REFRESH_HISTORY columns
SELECT 'MATERIALIZED_VIEW_REFRESH_HISTORY' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM SNOWFLAKE.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ACCOUNT_USAGE'
  AND TABLE_NAME = 'MATERIALIZED_VIEW_REFRESH_HISTORY'
ORDER BY ORDINAL_POSITION;

-- Check AUTOMATIC_CLUSTERING_HISTORY columns
SELECT 'AUTOMATIC_CLUSTERING_HISTORY' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM SNOWFLAKE.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ACCOUNT_USAGE'
  AND TABLE_NAME = 'AUTOMATIC_CLUSTERING_HISTORY'
ORDER BY ORDINAL_POSITION;

-- Check COPY_HISTORY columns
SELECT 'COPY_HISTORY' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM SNOWFLAKE.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ACCOUNT_USAGE'
  AND TABLE_NAME = 'COPY_HISTORY'
ORDER BY ORDINAL_POSITION;

-- Check PIPE_USAGE_HISTORY columns
SELECT 'PIPE_USAGE_HISTORY' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM SNOWFLAKE.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ACCOUNT_USAGE'
  AND TABLE_NAME = 'PIPE_USAGE_HISTORY'
ORDER BY ORDINAL_POSITION;

-- Summary: Check which tables exist
SELECT TABLE_NAME
FROM SNOWFLAKE.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'ACCOUNT_USAGE'
  AND TABLE_NAME IN (
    'MASKING_POLICIES',
    'ROW_ACCESS_POLICIES', 
    'PASSWORD_POLICIES',
    'SESSION_POLICIES',
    'EXTERNAL_ACCESS_HISTORY'
  )
ORDER BY TABLE_NAME;

